### ISSUE TITLE
Can't compile 1.1.1.0 on windows.

### ISSUE THREAD

**Issue by vagarenko** [bos/criterion#100]
Compilation fails with following message

```
[13 of 13] Compiling Criterion ( Criterion.hs, dist\dist-sandbox-9711dd26\build\Criterion.o )
cbits\cycles.c:55:2:
     error: #error Unsupported OS/architecture/compiler!
```

Version 1.1.0.0 compiles fine.
It looks like this commit is responsible https://github.com/bos/criterion/commit/0673606c70ba22234b8908a8f30e8ea588c6d776

Update: I have 32-bit GHC 7.10.2

**Comment by agrafix** [comment]
Some issue here with 32bit GHC7.10.3 on WIndows/Cygwin

**Comment by RyanGlScott** [comment]
@erikd, a quick search reveals [your PR](https://github.com/bos/criterion/pull/98) is responsible for this breakage. Is there an easy way to restore 32-bit Windows compatibility?

**Comment by erikd** [comment]
I'll take a look.

**Comment by erikd** [comment]
https://github.com/bos/criterion/pull/105 should fix it.

**Comment by rrnewton** [comment]
Does anyone have experience setting up CI for windows?  We're in good shape for linux testing now on travis, but that's it....

**Comment by RyanGlScott** [comment]
@rrnewton: I've [been experimenting](https://github.com/RyanGlScott/appveyor-cabal-test) with using [AppVeyor](https://www.appveyor.com/) for Windows CI builds. I still have a long ways to go to make it on par with the very well tested Travis CI scripts floaing around in the Haskellverse, but in theory AppVeyor should provide a very similar experience.

**Comment by rrnewton** [comment]
We used to have a windows VM hooked up to our in-house Jenkins setup.... but it was too much of a pain to keep up.  Someone could put bring it back up if they wanted, but AppVeyor sounds promising.

**Comment by vagarenko** [comment]
After PR #105 it compiles but tests fail:

```
alex@alex-PC MINGW64 /d/projects/criterion (Branch_3b6797b1fffa8b133d9a8577e17d34d3cd709d8e)
$ cabal test
Preprocessing library criterion-1.1.3.0...
Preprocessing test suite 'sanity' for criterion-1.1.3.0...
Preprocessing test suite 'tests' for criterion-1.1.3.0...
Running 2 test suites...
Test suite sanity: RUNNING...
benchmarking fib/fib 10
time                 4.464 us   (4.453 us .. 4.473 us)
                     1.000 Rsanity: [Failed]
ERROR: <stdout>: commitBuffer: invalid argument (invalid character)

         Test Cases  Total
 Passed  0           0
 Failed  1           1
 Total   1           1
Test suite sanity: FAIL
Test suite logged to: dist\test\criterion-1.1.3.0-sanity.log
Test suite tests: RUNNING...
Test suite tests: PASS
Test suite logged to: dist\test\criterion-1.1.3.0-tests.log
1 of 2 test suites (1 of 2 test cases) passed.
```

dist\test\criterion-1.1.3.0-sanity.log: 

```
Test suite sanity: RUNNING...
benchmarking fib/fib 10

time                 4.464 us   (4.453 us .. 4.473 us)

                     1.000 Rsanity: [Failed]

ERROR: <stdout>: commitBuffer: invalid argument (invalid character)



         Test Cases  Total 

 Passed  0           0     

 Failed  1           1     

 Total   1           1     

Test suite sanity: FAIL
Test suite logged to: dist\test\criterion-1.1.3.0-sanity.log
```

**Comment by erikd** [comment]
@vagarenko Thats a problem with the locale setup. The Criterion output requires UTF-8. Sorry, no idea how so set that up on Windows.

**Comment by vagarenko** [comment]
@erikd 

> Are you getting that same error on 64 bit Windows?
No I don't get compilation error anymore.

>That (invalid character) is a problem with the locale setup. The Criterion output requires UTF-8.
Oh. I thought that git bash console would handle utf properly but it failed.

> Sorry, no idea how so set that up on Windows.
It's `chcp 65001` command for windows console. After it all the tests succeeded.

Thanks for fix!

**Comment by RyanGlScott** [comment]
Perhaps it's worthwhile to modify the codepage before printing out to the screen in `criterion`. Something like:

```haskell
#if defined(mingw32_HOST_OS)
import Control.Exception (finally)
import System.Win32.Console (getConsoleCP, setConsoleCP)
#endif

-- | Run in a modified codepage where we can print UTF-8 values on Windows.
withUnicode :: IO a -> IO a
#if defined(mingw32_HOST_OS)
withUnicode m = do
  cp <- getConsoleCP
  (setConsoleCP 65001 >> m) `finally` setConsoleCP cp
#else
withUnicode m = m
#endif
```

This would require depending on the `Win32` package on Windows.

**Comment by agrafix** [comment]
@RyanGlScott sounds good to me!

**Comment by rrnewton** [comment]
@RyanGlScott sounds good to me too.  I don't have a windows box to test atm, but if you can confirm that works, please commit it on iu-parfunc/criterion or send a PR.

**Comment by danilaml** [comment]
On Win10 x64, GHC 8.0.1 tests fail for me with ` 1.000 Rtt: <stdout>: commitBuffer: invalid argument (invalid character)`

**Comment by erikd** [comment]
@danilaml `invalid argument (invalid character)` is due to criterion requiring UTF-8. See above.

**Comment by NicolasT** [comment]
FWIW, if you want Windows CI through AppVeyor, here's a configuration file that suits my needs (except for now because Criterion 1.1.1.0 is broken on Win32 ;-)): https://github.com/NicolasT/reedsolomon/blob/master/appveyor.yml
You'll most likely not need to install autotools and make, not need to run `autoreconf` etc.

**Comment by ppelleti** [comment]
See also [Harendra Kumar's post][1] about [package-test][2], which supports AppVeyor.  I've been trying it out, but my build failed because of Criterion, which is how I ended up here.  😃

[1]: https://mail.haskell.org/pipermail/haskell-cafe/2016-October/125251.html
[2]: https://github.com/harendra-kumar/package-test

**Comment by bos** [comment]
Hopefully this is fixed with the release of 1.1.4.0.
